Add Support for GE Water Filters
simbaja/ha_components pull request #16
Opened 2021-06-28 16:27 UTC by bendavis

Add initial read only support for GE Water Filters. 

Right now added sensors for mode of the filter, filter life, and addition to flow rate & day usage.

HA Integration:
![wh_filter_ha](https://user-images.githubusercontent.com/532255/123670912-55263180-d803-11eb-8099-d3ad81a7af29.png)

2021-06-30 17:32 UTC, simbaja requested changes

2021-06-30 17:32 UTC, simbaja commented on custom_components/ge_home/update_coordinator.py
> +            await asyncio.sleep(
I'm seeing things like this throughout - guessing you're using a code formatter.  Can you update it to not perform this particular type of reformat?

2021-06-30 17:32 UTC, simbaja commented on custom_components/ge_home/entities/waterfilter/filter_life_remaining.py
> +class ErdFilterLifeRemainingSensor(GeErdSensor):
just to stick with conventions, can you prefix the new entity types with Ge?

2021-06-30 20:22 UTC, simbaja commented
Great job adding this support and thanks for the contribution!!  Just a few minor changes requested and we can get this merged into the code.

2021-07-01 13:51 UTC, bendavis commented
I make these changes - I also noticed ( when loading on my main instance with HACS) that some of the imports are wrong. I'll push that up too.

2021-07-08 15:12 UTC, simbaja commented
Any updates on the changes?  You mentioned adding some additional bugfixes so didn't want to just push this over and fix up the couple of comments.

2021-07-08 18:58 UTC, merged